# show uptime
echo "Uptime: $(uptime)"

# NVM
# Manage multiple Node.js versions.
export NVM_DIR="$HOME/.nvm"
  [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

###-tns-completion-start-###
if [ -f ~/.tnsrc ]; then 
    source ~/.tnsrc 
fi

###-tns-completion-end-###
export ANDROID_HOME=/usr/local/share/android-sdk
export LC_ALL="en_US.UTF-8"

# composer
# PHP dependency manager
export PATH="$HOME/.composer/vendor/bin:$PATH"

# homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"
